
delete from [USER] where USERNAME = 'admin'

insert into [USER] values ('admin','admin@doamin','p',0) 
select * from [PRODUCTSTOCK]

select u.USERNAME, u.Email, (p.QTY)
from [USER] as u, PURCHASEHISTORY as p
where u.USERNAME = p.USERNAME

select * from APPROVEDPRODUCTS

SELECT [USER].USERNAME, [USER].EMAIL, max(PURCHASEHISTORY.QTY)
                            FROM [USER], PURCHASEHISTORY
                            WHERE [USER].USERNAME = [PURCHASEHISTORY].USERNAME
							GROUP BY [USER].USERNAME, [USER].EMAIL;

SELECT a.PRODUCTNAME, a.PRODUCTPRICE, a.PRODUCTCAT,  avg(p.QTY)
FROM APPROVEDPRODUCTS AS a, PURCHASEHISTORY AS p
WHERE a.PID = p.PID
GROUP BY a.PRODUCTNAME, a.PRODUCTPRICE, a.PRODUCTCAT;

select * from STORES
select * from PRODUCTSTOCK 

select * from [USER] 
select OWNERUSR, STORENAME 
from STORES as s, [USER] as u
where u.USERNAME = s.OWNERUSR and u.USERNAME = 'merchant'

select * from PRODUCTSTOCK

INSERT into STOREACTIONS ([SID], [STATEMENT], PID) values (4,'action',2)

SELECT sa.AID, sa.[SID], ap.PRODUCTNAME, sa.[STATEMENT]
FROM STOREACTIONS AS sa, APPROVEDPRODUCTS AS ap
WHERE sa.PID = ap.PID AND sa.[SID] IN (SELECT [SID] FROM STORES WHERE STORES.STORENAME = 'store1')

SELECT STORES.[SID], STORES.STORENAME, STOREACTIONS.AID, STOREACTIONS.[STATEMENT], STOREACTIONS.PID, APPROVEDPRODUCTS.PRODUCTNAME
FROM STORES, STOREACTIONS, APPROVEDPRODUCTS
WHERE STOREACTIONS.PID = APPROVEDPRODUCTS.PID AND STORES.[SID] IN (SELECT [SID] FROM STORES WHERE STORES.STORENAME = 'store2')

SELECT PRODUCTNAME 
FROM APPROVEDPRODUCTS, PRODUCTSTOCK
WHERE APPROVEDPRODUCTS.PID = PRODUCTSTOCK.PID
AND PRODUCTSTOCK.[SID] IN ( SELECT [SID] FROM STORES 
WHERE STORENAME = 'store1' AND OWNERUSR = 'merchant')

SELECT * FROM APPROVEDPRODUCTS

DELETE FROM STOREACTIONS WHERE [SID] = 10

SELECT QTY FROM PRODUCTSTOCK
                           WHERE [SID] IN ( SELECT [SID] FROM STORES
                           WHERE STORENAME = 'new store' AND OWNERUSR = 'merchant')
                           AND PID IN ( SELECT PID FROM APPROVEDPRODUCTS
                           WHERE PRODUCTNAME = 'prodtest2')